language: go
go:
  - 1.9
# Don't email me the results of the test runs.
notifications:
  email: false
before_script:
  - go get github.com/golang/lint/golint                        # Linter

script:
  - go test -v -race ./...                   # Run all the tests with the race detector enabled
  - go vet ./...                             # go vet is the official Go static analyzer
  - golint -set_exit_status $(go list ./...) # one last linter